"""Update models nullable Message

Revision ID: 61c9da1bf081
Revises: b92c867ad8fe
Create Date: 2025-04-11 19:00:49.273702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61c9da1bf081'
down_revision: Union[str, None] = 'b92c867ad8fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'sender_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('messages', 'received_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'received_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('messages', 'sender_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
